# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  #- osx

julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - sudo apt-get update
  - sudo apt-get install python-matplotlib

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

script:
  #- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  #- if [[ `uname` = "Darwin" ]]; then JULIA="julia"; else JULIA="xvfb-run julia"; fi;
  #- LD_PRELOAD=${HOME}/.julia/v0.6/Conda/deps/usr/lib/libz.so julia -e 'Pkg.clone(pwd()); Pkg.build("Shearlab"); Pkg.test("Shearlab"; coverage=true)'; 
  #- julia -e 'ENV["PYTHON"]="python"; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot"); Pkg.build("PyPlot"); Pkg.add("DSP"); Pkg.build("DSP");Pkg.clone(pwd()); Pkg.build("Shearlab"); Pkg.test("Shearlab"; coverage=true)';

after_success:
- julia -e 'cd(Pkg.dir("Shearlab")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'


